#!/bin/bash

# Read the input TSV file (log file)
while IFS=$'\t' read -r host logname time method url response bytes; do
    # Use the host if available, otherwise use the IP address
    hostname="${host:-$host}"
    
    # Increment the count for each hostname/IP in the associative array
    ((hosts_count["$hostname"]++))
done < "$1"

# Print the top 11 hosts/IPs with the most requests
for hostname in "${!hosts_count[@]}"; do
    printf "%s\n" "$hostname"
done | sort -rnk2 | head -n 11
